# Generated by Django 5.0.7 on 2024-07-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_alter_fotografia_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fotografia',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
